### ISSUE TITLE
Window maximizing problem on GNOME 44-44.1 after Wayland socket

### ISSUE THREAD

**Issue by Dhizaes** [flathub/com.discordapp.Discord#291]
After 0.0.27 and Wayland update, i decided to enable Wayland socket. Whenever i open Discord with Wayland socket enabled, maximize button maximizes Discord but adds spaces to right, left, and bottom of its window. Also adds extra space to top but it looks like it is "extra" title bar. I'm not sure what is causing this so i decided to open this as issue. 

![Broken maximized window on Wayland GNOME](https://user-images.githubusercontent.com/16524806/235103721-8dd7a03a-cbed-4673-93c7-048a19df47fb.png)

Note that i tried to test this socket on GNOME 44.0 first, then i upgraded my OS and i've get 44.1, it has that same issue, like in screenshot. I don't have this problem if i keep Wayland socket disabled.

Edit: Right and left window snapping makes that exact problem too, but in a weird way. When i snap it to right, half of the window is out of range, top bar is the same, bottom bar creates ghost part and it looks like it is snapped but it is transparent. After that snap, i can't snap it anymore. 

CPU: Ryzen 5 3600
GPU: NVIDIA RTX 3060
OS: Fedora 38, up-to-date always

**Comment by lionirdeadman** [comment]
I can't reproduce this here on GNOME 44, on Wayland, on Fedora 38.

Could this be due to an extension? :thinking:

**Comment by Dhizaes** [comment]
I tried to disable extensions completely, logget out/logged in, nothings changed. Tried to change GNOME theme to default one too, it didn't work either. Also it crashes so much if Wayland socket is enabled. Even if it works without crash, errors in terminal is the same as crashed one. Crash looks like NVIDIA related, it searches for GBM related files and values but it is already works with GBM, so how it can't find it? I'm not sure what is happening since errors are the same. I think i can't blame NVIDIA for just windowing problems, it works without any problem when i disable Wayland socket. Fedora crash report says it is completed with SIGTRAP. What can i provide to learn more or solve this?

**Comment by Dhizaes** [comment]
Tried to open Discord with Wayland socket since its been a while. There is no fullscreen problem right now, at least for me. Only problem is that i can't use right and left snap points for Discord window. Other apps works fine.

GPU: NVIDIA RTX 3060, 545.x version driver
OS: Fedora 39
GNOME Version: 45.2

**Comment by scaledteam** [comment]
I don't think so, it was fixed long time ago, but resizing in wayland version is still janky in general. I stopped using this software months ago though.

**Comment by guihkx** [comment]
Alright, thank you for your input.

Even though I don't think this issue is specific to the Flatpak package (i.e. a fix would likely not be possible here), I'll wait a bit more to see if anyone is still experiencing this bug in newer versions of GNOME.

Otherwise, I'll close it.

**Comment by thatLeaflet** [comment]
I've not experienced this issue in a while. There are still some Wayland issues, such as right clicking the titlebar not bringing up Gnome's menu and sometimes clicking the titlebar activates the window behind Discord.

But these issues are not related directly to Discord, they are shared with other Electron apps with Wayland enabled, like Bitwarden.

**Comment by guihkx** [comment]
Yeah, unfortunately I noticed a bunch of old, Wayland-only issues that still happen to this day.

In any case, thank you for confirming that this one in particular hasn't happened anymore.
